# Generated by Django 4.2.1 on 2023-05-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_pass', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
            ],
        ),
    ]
