# Generated by Django 4.2.1 on 2023-05-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_riss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_mail', models.CharField(max_length=255)),
                ('user_pass', models.CharField(max_length=255)),
            ],
        ),
    ]
