# Generated by Django 4.2.1 on 2023-05-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_riss', '0002_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_cat', models.CharField(max_length=255)),
                ('p_price', models.CharField(max_length=255)),
                ('p_quant', models.CharField(max_length=255)),
            ],
        ),
    ]
